apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      NodePort: 30000
  type: LoadBalancer
  